remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Pranav K Anupam
discription: This is my personal Webpage for hosting my blog and my portfolio.
minima:  
  social_links:
    twitter: _itspranav
    github: panupam
    facebook: pranavkanupam
    instagram: _itspranav
    email: kumarpranav033@gmail.com
    linkedin: pranavkanupam

github: [metadata]

